# Generated by Django 4.2.6 on 2023-10-09 03:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('oid', models.UUIDField(blank=True, db_column='oid_product', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.UUIDField(blank=True)),
                ('price', models.FloatField(max_length=10, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('lenght', models.SmallIntegerField()),
                ('category_oid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
